test:
    assemblyPath: ../test/Lupi.Examples.dll
    singleTestClassInstance: true
    testClass: Lupi.Examples.InMemory
listeners:
    activeListeners:
    - file
    - statsd
    - console
    file:
        path: ${RESULT_PATH}
    statsd:
        host: ${STATSD_HOST}
        port: ${STATSD_PORT}

