test:
    assemblyPath: ../test/Lupi.Examples.dll
    singleTestClassInstance: true
    testClass: Lupi.Examples.InMemory
listeners:
    activeListeners:
    - file
    - statsd
    - console
    file:
        path: results.log
    statsd:
        host: 127.0.0.1
        port: 8125
        prefix: Lupi.Examples
